// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace QuanLyKho.Models
{
    public partial class PhieuNhap
    {
        public PhieuNhap()
        {
            list_chiTietPhieuNhap = new HashSet<ChiTietPhieuNhap>();
        }
        public int soPhieu { get; set; }
        public DateTime ngayLap { get; set; }
        public string maKho { get; set; }

        public virtual Kho khoNavigation { get; set; }
        public virtual ICollection<ChiTietPhieuNhap> list_chiTietPhieuNhap { get; set; }
    }
}