// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace QuanLyKho.Models
{
    public partial class VatTu
    {
        public VatTu()
        {
            list_chiTietPhieuNhap = new HashSet<ChiTietPhieuNhap>();
        }

        public string maVatTu { get; set; }
        public string tenVatTu { get; set; }
        public string donViTinh { get; set; }
        public string anhVatTu { get; set; }
        public string xuatXu { get; set; }

        public virtual ICollection<ChiTietPhieuNhap> list_chiTietPhieuNhap { get; set; }
    }
}